[package]
name = "nanobatch"
version = "0.1.0"
authors = ["Oliver Daff <oliverdaff@users.noreply.github.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["rt-core", "macros", "blocking" ] }

[dev-dependencies]
tokio-test = "*"